# Generated by Django 4.2.2 on 2024-05-07 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
